# Generated by Django 4.2.7 on 2023-11-01 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='date_of_birth',
        ),
        migrations.AddField(
            model_name='user',
            name='full_name',
            field=models.CharField(default=12901, max_length=45, unique=True),
        ),
    ]
