# Generated by Django 4.2.7 on 2023-11-22 07:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Main_page', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contactusmodel',
            options={'verbose_name': 'user feedback', 'verbose_name_plural': 'user feedbacks'},
        ),
    ]
