# Generated by Django 4.2.7 on 2023-11-22 08:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Main_page', '0003_alter_contactusmodel_date_alter_contactusmodel_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactusmodel',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to=settings.AUTH_USER_MODEL),
        ),
    ]
