# Generated by Django 4.2.7 on 2023-11-22 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main_page', '0004_alter_contactusmodel_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactusmodel',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
