# Generated by Django 4.2.7 on 2023-11-22 11:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Main_page', '0005_alter_contactusmodel_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutUs_Model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pottage', models.ImageField(blank=True, null=True, upload_to='images/aboutus_title')),
                ('general_description', models.TextField(verbose_name='General description')),
            ],
        ),
        migrations.CreateModel(
            name='BigDescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('text', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='site_gemeral_info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('website_name', models.CharField(max_length=50, verbose_name='website name')),
                ('email_address', models.EmailField(max_length=254, verbose_name='Email address')),
                ('alternative_email_address', models.EmailField(blank=True, max_length=254, null=True, verbose_name='second Email address (optional)')),
                ('phone_number', models.CharField(max_length=20, verbose_name='phone number')),
                ('alternative_phone_number', models.CharField(blank=True, max_length=20, null=True, verbose_name='second phone number (optional)')),
                ('company_address', models.TextField(verbose_name='company address')),
                ('insa_url', models.CharField(blank=True, max_length=255, null=True, verbose_name='instagram')),
                ('fb_url', models.CharField(blank=True, max_length=255, null=True, verbose_name='facebook')),
                ('pin_url', models.CharField(blank=True, max_length=255, null=True, verbose_name='pinterest')),
                ('in_url', models.CharField(blank=True, max_length=255, null=True, verbose_name='linkedin')),
                ('twitter_url', models.CharField(blank=True, max_length=255, null=True, verbose_name='twitter')),
            ],
            options={
                'verbose_name': 'website general information',
            },
        ),
        migrations.AlterField(
            model_name='contactusmodel',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='messages', to=settings.AUTH_USER_MODEL),
        ),
    ]
