# Generated by Django 4.2.7 on 2023-11-28 10:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Main_page', '0006_aboutus_model_bigdescription_site_gemeral_info_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BigDescription',
        ),
    ]
