# Generated by Django 4.2.7 on 2024-01-05 20:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Main_page', '0007_delete_bigdescription'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='site_gemeral_info',
            new_name='site_general_info',
        ),
    ]
