# Generated by Django 4.2.7 on 2024-01-05 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main_page', '0008_rename_site_gemeral_info_site_general_info'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aboutus_model',
            options={'verbose_name': 'about us info', 'verbose_name_plural': 'about us info`s'},
        ),
        migrations.AddField(
            model_name='aboutus_model',
            name='A_column',
            field=models.CharField(help_text='2 recommended', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='aboutus_model',
            name='A_column_title',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='aboutus_model',
            name='B_column',
            field=models.CharField(help_text='3 recommended', max_length=90, null=True),
        ),
        migrations.AddField(
            model_name='aboutus_model',
            name='B_column_title',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='aboutus_model',
            name='C_column',
            field=models.CharField(help_text='4 recommended', max_length=80, null=True),
        ),
        migrations.AddField(
            model_name='aboutus_model',
            name='C_column_title',
            field=models.CharField(max_length=40, null=True),
        ),
    ]
