# Generated by Django 4.2.7 on 2024-02-14 20:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Main_page', '0009_alter_aboutus_model_options_aboutus_model_a_column_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aboutus_model',
            options={'verbose_name': 'about us info', 'verbose_name_plural': 'about us information'},
        ),
    ]
