# Generated by Django 4.2.7 on 2024-02-27 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main_page', '0010_alter_aboutus_model_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aboutus_model',
            options={'verbose_name': 'about us page'},
        ),
        migrations.RemoveField(
            model_name='aboutus_model',
            name='A_column',
        ),
        migrations.RemoveField(
            model_name='aboutus_model',
            name='A_column_title',
        ),
        migrations.RemoveField(
            model_name='aboutus_model',
            name='B_column',
        ),
        migrations.RemoveField(
            model_name='aboutus_model',
            name='B_column_title',
        ),
        migrations.RemoveField(
            model_name='aboutus_model',
            name='C_column',
        ),
        migrations.RemoveField(
            model_name='aboutus_model',
            name='C_column_title',
        ),
        migrations.AddField(
            model_name='aboutus_model',
            name='A_1_body',
            field=models.TextField(blank=True, null=True, verbose_name='first Paragraph'),
        ),
        migrations.AddField(
            model_name='aboutus_model',
            name='A_1_title',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='first Paragraph title'),
        ),
        migrations.AddField(
            model_name='aboutus_model',
            name='A_2_body',
            field=models.TextField(blank=True, null=True, verbose_name='second paragraph'),
        ),
        migrations.AddField(
            model_name='aboutus_model',
            name='A_2_title',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='second paragraph title'),
        ),
        migrations.AddField(
            model_name='aboutus_model',
            name='B_1_body',
            field=models.TextField(blank=True, null=True, verbose_name='small paragraph 1'),
        ),
        migrations.AddField(
            model_name='aboutus_model',
            name='B_1_title',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='small paragraph title 1'),
        ),
        migrations.AddField(
            model_name='aboutus_model',
            name='B_2_body',
            field=models.TextField(blank=True, null=True, verbose_name='small paragraph 2'),
        ),
        migrations.AddField(
            model_name='aboutus_model',
            name='B_2_title',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='small paragraph title 2'),
        ),
        migrations.AddField(
            model_name='aboutus_model',
            name='B_3_body',
            field=models.TextField(blank=True, null=True, verbose_name='small paragraph 3'),
        ),
        migrations.AddField(
            model_name='aboutus_model',
            name='B_3_title',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='small paragraph title 3'),
        ),
        migrations.AddField(
            model_name='aboutus_model',
            name='visibility',
            field=models.BooleanField(default=True, unique=True, verbose_name='set as current info'),
        ),
    ]
