# Generated by Django 4.2.7 on 2024-02-27 22:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Main_page', '0011_alter_aboutus_model_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aboutus_model',
            name='visibility',
        ),
    ]
