# Generated by Django 4.2.7 on 2024-01-05 16:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Blog_Post', '0003_usercomments'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usercomments',
            options={'verbose_name': 'Comment', 'verbose_name_plural': 'Comments'},
        ),
    ]
