# Generated by Django 4.2.7 on 2024-02-02 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog_Post', '0006_remove_usercomments_sub_comment_usercomments_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercomments',
            name='name',
            field=models.CharField(default='user', max_length=50),
        ),
    ]
