# Generated by Django 4.2.7 on 2024-02-14 21:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Blog_Post', '0008_post_tags'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='tags',
            new_name='tag',
        ),
    ]
