# Generated by Django 4.2.7 on 2024-02-14 21:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Blog_Post', '0009_rename_tags_post_tag'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='tag',
            new_name='tags',
        ),
    ]
