# Generated by Django 4.2.7 on 2024-02-18 19:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Blog_Post', '0010_rename_tag_post_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercomments',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replay', to='Blog_Post.usercomments'),
        ),
    ]
