# Generated by Django 4.2.7 on 2024-02-19 10:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Blog_Post', '0012_alter_usercomments_parent'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usercomments',
            options={'ordering': ['-created_date'], 'verbose_name': 'Comment', 'verbose_name_plural': 'Comments'},
        ),
        migrations.RemoveField(
            model_name='usercomments',
            name='parent',
        ),
        migrations.CreateModel(
            name='ReplyComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(default='user', max_length=50)),
                ('subject', models.CharField(blank=True, max_length=50, null=True)),
                ('body', models.TextField(max_length=800)),
                ('email', models.EmailField(max_length=254)),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='replys', to=settings.AUTH_USER_MODEL)),
                ('parent_comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='replys', to='Blog_Post.usercomments')),
            ],
            options={
                'verbose_name': 'reply',
                'verbose_name_plural': 'replys',
                'ordering': ['-created_date'],
            },
        ),
    ]
