# Generated by Django 4.2.7 on 2024-02-21 19:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Blog_Post', '0013_alter_usercomments_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercomments',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reply', to='Blog_Post.usercomments'),
        ),
        migrations.DeleteModel(
            name='ReplyComment',
        ),
    ]
