# Generated by Django 4.2.7 on 2024-02-27 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog_Post', '0014_usercomments_parent_delete_replycomment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercomments',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='usercomments',
            name='name',
            field=models.CharField(blank=True, default='user', max_length=50, null=True),
        ),
    ]
