# Generated by Django 4.2.7 on 2024-03-24 10:44

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Blog_Post', '0020_rename_bookmarked_post_bookmarks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='BookMarks',
            field=models.ManyToManyField(blank=True, related_name='bookmarked', to=settings.AUTH_USER_MODEL, verbose_name='bookmarked by '),
        ),
        migrations.AlterField(
            model_name='post',
            name='like',
            field=models.ManyToManyField(blank=True, related_name='likes', to=settings.AUTH_USER_MODEL),
        ),
    ]
